# Configuration de build globale
[build]
  # Commande pour construire le workspace 'frontend'
  command = "yarn workspace frontend build"
  # Dossier contenant les fichiers statiques du frontend après le build
  publish = "frontend/dist"
  # Dossier où se trouvent nos fonctions serverless
  functions = "backend/functions"

# Configuration pour les fonctions
[functions]
  external_node_modules = ["firebase-admin", "dotenv"]
  node_bundler = "esbuild"

# Configuration pour le serveur de développement local
[dev]
  # Port pour le serveur de développement unifié. 8888 est une alternative commune.
  port = 8888
  # Netlify Dev détectera automatiquement le serveur Vite du workspace 'frontend'
  # car nous n'écrasons plus sa configuration avec 'publish'.

# Redirige les appels API vers notre fonction serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Règle de fallback pour les applications Single Page (SPA) comme React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
